#ifndef _EL_SERVICEDEFS_H_
#define _EL_SERVICEDEFS_H_

#define _IMPROVED_PACKET_ENCRYPTION_
//#define __PERFORMANCE_CHECK__

#define ENABLE_ACCE_COSTUME_SYSTEM
#define ENABLE_PLAYER_PER_ACCOUNT5
#define ENABLE_WOLFMAN_CHARACTER
#define ENABLE_CHEQUE_SYSTEM

#endif //_EL_SERVICEDEFS_H_
//martysama0134's 2e58d0b8baeb072acdf3afc4a5d1999f
